//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinpan.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KinpanEntities : DbContext
    {
        public KinpanEntities()
            : base("name=KinpanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_KinpanWard> t_KinpanWard { get; set; }
        public virtual DbSet<t_KinpanImgDetail> t_KinpanImgDetail { get; set; }
        public virtual DbSet<t_KinpanProList> t_KinpanProList { get; set; }
        public virtual DbSet<t_KinpanDetails> t_KinpanDetails { get; set; }
    }
}
