//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinpan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_KinpanProList
    {
        public int id { get; set; }
        public string ProID { get; set; }
        public int SalesPriceType { get; set; }
        public string ProDetailsUrl { get; set; }
        public string DesignCompanyUrl { get; set; }
        public string ProImgUrl { get; set; }
        public double SalesPrice { get; set; }
        public int Views { get; set; }
        public string ProName { get; set; }
        public string DesignCompany { get; set; }
        public string CompanyType { get; set; }
        public string ProImgSavePath { get; set; }
        public string Oth { get; set; }
    }
}
