//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinpan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_KinpanImgDetail
    {
        public int id { get; set; }
        public string ProID { get; set; }
        public string ProImgUrl { get; set; }
        public int ProImgType { get; set; }
        public string ProImgSavaPath { get; set; }
        public string ProImgTitle { get; set; }
        public string Oth { get; set; }
    }
}
